In [1]:
import numpy as np
import pandas as pd

In [2]:
data={
    'Name':['safeer','ahmad','tahir'],
    'Age':[21,20,22],
    'city':['DIKhan','Islamabad','karachi'],
    'salary':[20000,40000,30000]
}

In [3]:
pd.DataFrame(data)

     Name  Age       city  salary
0  safeer   21     DIKhan   20000
1   ahmad   20  Islamabad   40000
2   tahir   22    karachi   30000

In [4]:
#creating dataframes through list
data_list=[['safeer',21,'DIKhan',20000], 
           ['ahmad',20,'Islambad',40000],
           ['tahir',22,'karachi',30000]
        ]
column=['Name','Age','City','Salary']

In [5]:
df=pd.DataFrame(data_list,columns=column)
print(df)

     Name  Age      City  Salary
0  safeer   21    DIKhan   20000
1   ahmad   20  Islambad   40000
2   tahir   22   karachi   30000

In [6]:
print(df.loc[0])#it will return one or more specific rows

Name      safeer
Age           21
City      DIKhan
Salary     20000
Name: 0, dtype: object

In [7]:
#selecting one column
df['Name']

0    safeer
1     ahmad
2     tahir
Name: Name, dtype: str

In [8]:
#selecting two columns
df[['Name','City']]

     Name      City
0  safeer    DIKhan
1   ahmad  Islambad
2   tahir   karachi

In [9]:
#adding a new column
df['Designation']=['Developer','Manager','Tester']

In [10]:
df

     Name  Age      City  Salary Designation
0  safeer   21    DIKhan   20000   Developer
1   ahmad   20  Islambad   40000     Manager
2   tahir   22   karachi   30000      Tester

In [11]:
#removing column from data set
df.drop('Designation',axis=1)

     Name  Age      City  Salary
0  safeer   21    DIKhan   20000
1   ahmad   20  Islambad   40000
2   tahir   22   karachi   30000

In [12]:
df.drop('Designation',axis=1,inplace=True)#remove the column from data set permanently

In [13]:
df

     Name  Age      City  Salary
0  safeer   21    DIKhan   20000
1   ahmad   20  Islambad   40000
2   tahir   22   karachi   30000

In [14]:
#removing multiple columns from data set
df.drop(['Age','City'],axis=1)

     Name  Salary
0  safeer   20000
1   ahmad   40000
2   tahir   30000

In [15]:
#removing row from the table
df.drop(1,axis=0)

     Name  Age     City  Salary
0  safeer   21   DIKhan   20000
2   tahir   22  karachi   30000

 ``` Selection Of rows and ```

In [16]:
#selecting subsets of rows and columns
df.loc[[0,2]][['City','Salary']]

      City  Salary
0   DIKhan   20000
2  karachi   30000

In [17]:
#conditional selection
df[(df['Age']<22) & (df['City']=='DIKhan')]

     Name  Age    City  Salary
0  safeer   21  DIKhan   20000