In [1]:
import numpy as np
import pandas as pd

"""Merging"""

In [2]:
Employee=pd.DataFrame({
    'Employee_id':[12,43,45,56,76],
    'Employee_name':['safeer','khan','fahad','tahir','saad_cholla'],
    'Department':['Data Science','Data Analyst','Wela','lull stack developer','washroom']
})
Employee

   Employee_id Employee_name            Department
0           12        safeer          Data Science
1           43          khan          Data Analyst
2           45         fahad                  Wela
3           56         tahir  lull stack developer
4           76   saad_cholla              washroom

In [3]:
Salaries=pd.DataFrame({
    'Employee_id':[12,43,45,56,76,54,98],
    'Salary':[20000,40000,60000,80000,70000,30000,100000],
    'Bonus':[10000,23000,45000,12000,34000,6000,70000]
})
Salaries

   Employee_id  Salary  Bonus
0           12   20000  10000
1           43   40000  23000
2           45   60000  45000
3           56   80000  12000
4           76   70000  34000
5           54   30000   6000
6           98  100000  70000

In [4]:
pd.merge(Employee,Salaries,on='Employee_id',how='inner')#keeps the intersection of the keys e.g (Employee_id)

   Employee_id Employee_name            Department  Salary  Bonus
0           12        safeer          Data Science   20000  10000
1           43          khan          Data Analyst   40000  23000
2           45         fahad                  Wela   60000  45000
3           56         tahir  lull stack developer   80000  12000
4           76   saad_cholla              washroom   70000  34000

In [5]:
pd.merge(Employee,Salaries,on='Employee_id',how='outer')#doing the union of the all rows in both dataframes

   Employee_id Employee_name            Department  Salary  Bonus
0           12        safeer          Data Science   20000  10000
1           43          khan          Data Analyst   40000  23000
2           45         fahad                  Wela   60000  45000
3           54           NaN                   NaN   30000   6000
4           56         tahir  lull stack developer   80000  12000
5           76   saad_cholla              washroom   70000  34000
6           98           NaN                   NaN  100000  70000

In [6]:
pd.merge(Employee,Salaries,on='Employee_id',how='left')#left means merge on the basis of left dataframes eg like employee

   Employee_id Employee_name            Department  Salary  Bonus
0           12        safeer          Data Science   20000  10000
1           43          khan          Data Analyst   40000  23000
2           45         fahad                  Wela   60000  45000
3           56         tahir  lull stack developer   80000  12000
4           76   saad_cholla              washroom   70000  34000

In [7]:
pd.merge(Employee,Salaries,on='Employee_id',how='right')#right means merge on the basis of right dataframe eg like salaries

   Employee_id Employee_name            Department  Salary  Bonus
0           12        safeer          Data Science   20000  10000
1           43          khan          Data Analyst   40000  23000
2           45         fahad                  Wela   60000  45000
3           56         tahir  lull stack developer   80000  12000
4           76   saad_cholla              washroom   70000  34000
5           54           NaN                   NaN   30000   6000
6           98           NaN                   NaN  100000  70000

"""Concatination"""

In [8]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [9]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [10]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [11]:
#concatinating the two dataframes in columns 
pd.concat([df1,df2])# we will always provide a list to the concatinate function

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [12]:
#concatinate the two dataframes in rowsp
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

"""Joining"""

In [13]:
Frame1=pd.DataFrame({
    "name":["bob","Alice","Charlie"]
},index=[1,2,3])

In [14]:
Frame2=pd.DataFrame({
    "Score":[87,98,85]
},index=[2,3,4])

In [15]:
Frame1.join(Frame2)

      name  Score
1      bob    NaN
2    Alice   87.0
3  Charlie   98.0

In [16]:
Frame2.join(Frame1,how="outer")

   Score     name
1    NaN      bob
2   87.0    Alice
3   98.0  Charlie
4   85.0      NaN