In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

"""Seaching missing values"""

In [3]:
DF=pd.DataFrame(data)
DF

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [4]:
DF.isna()#this will return valid as false and null as true

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [5]:
DF.isna().sum()#sum all the null values in a columns

A    1
B    0
C    2
D    3
dtype: int64

In [6]:
DF.isna().any()# return true if there is any null value in the column and return false if there is none

A     True
B    False
C     True
D     True
dtype: bool

In [7]:
DF.notna()#it will return valid as true and null as false

       A     B      C      D
0   True  True   True   True
1   True  True   True  False
2  False  True   True  False
3   True  True  False  False
4   True  True  False   True

"""Removing missing values"""

In [8]:
DF.dropna()#remove all rows which contains null values

     A  B    C    D
0  1.0  1  1.0  1.0

In [9]:
DF.dropna(how='all')#remove those rows which contains all null values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [10]:
DF.dropna(axis=1)#remove columns which contains null value

   B
0  1
1  2
2  3
3  4
4  5

In [11]:
DF.dropna(thresh=3)#remove rows which contains N number of non-NULL values

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

""" Filling missing values"""

In [12]:
DF.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [13]:
values={'A':0,'B':1,'C':2,'D':3}#filling different values in all columns
DF.fillna(value=values)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  0.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [14]:
#filling mean inplace of null values
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0