In [25]:
import numpy as np 
import pandas as pd

"""OPerations"""

In [26]:
df=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':[10,None,12,13,14],
    'C':[15,16,17,18,19]
})
df

   A     B   C
0  1  10.0  15
1  2   NaN  16
2  3  12.0  17
3  4  13.0  18
4  5  14.0  19

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       4 non-null      float64
 2   C       5 non-null      int64
dtypes: float64(1), int64(2)
memory usage: 252.0 bytes

In [28]:
df.describe()

              A          B          C
count  5.000000   4.000000   5.000000
mean   3.000000  12.250000  17.000000
std    1.581139   1.707825   1.581139
min    1.000000  10.000000  15.000000
25%    2.000000  11.500000  16.000000
50%    3.000000  12.500000  17.000000
75%    4.000000  13.250000  18.000000
max    5.000000  14.000000  19.000000

"""DataFrame Applying Functions"""

In [29]:
def Cube(c):
    return c**3

In [30]:
df['A'].apply(Cube)

0      1
1      8
2     27
3     64
4    125
Name: A, dtype: int64

In [31]:
df

   A     B   C
0  1  10.0  15
1  2   NaN  16
2  3  12.0  17
3  4  13.0  18
4  5  14.0  19

In [32]:
#if we want to add new columnjhten we will store these values in new column
df['D']=df['A'].apply(Cube)

In [33]:
df

   A     B   C    D
0  1  10.0  15    1
1  2   NaN  16    8
2  3  12.0  17   27
3  4  13.0  18   64
4  5  14.0  19  125

In [ ]:
#we can also use lambda funtion instead of making own function
df['A']=df['A'].apply(lambda c : c**2)

In [36]:
df

    A     B   C    D
0   1  10.0  15    1
1   4   NaN  16    8
2   9  12.0  17   27
3  16  13.0  18   64
4  25  14.0  19  125