In [1]:
import numpy as np 
import pandas as pd

In [2]:
df=pd.read_csv("stock_data.csv")
df

            Date    Open    High     Low         Close  Adj Close       Volume
0    May 8, 2026  192.58  198.00  190.21        195.95     195.95   20,579,655
1    May 1, 2026  166.42  200.15  166.15        195.95     195.95  163,911,400
2    Apr 9, 2026     NaN     NaN     NaN  0.5 Dividend        NaN          NaN
3    Apr 1, 2026  149.09  189.18  134.57        161.39     160.83  651,513,600
4    Mar 1, 2026  141.62  171.76  136.95        147.11     146.60  621,098,900
5    Feb 1, 2026  170.92  171.20  135.25         145.4     144.89  578,683,700
6    Jan 9, 2026     NaN     NaN     NaN  0.5 Dividend        NaN          NaN
7    Jan 1, 2026  197.47  207.80  161.52        164.58     163.57  470,011,900
8    Dec 1, 2025  200.50  225.32  177.07        194.91     193.72  690,949,100
9    Nov 1, 2025  265.24  265.62  185.63        201.95     200.72  447,111,600
10   Oct 9, 2025     NaN     NaN     NaN  0.5 Dividend        NaN          NaN
11   Oct 1, 2025  278.80  322.54  256.28        262.61     260.55  483,229,200
12   Sep 1, 2025  222.00  345.72  218.79        281.24     279.04  771,912,000
13   Aug 1, 2025  247.83  258.49  223.11        226.13     224.36  218,404,000
14  Jul 10, 2025     NaN     NaN     NaN  0.5 Dividend        NaN          NaN
15   Jul 1, 2025  219.30  260.87  216.31        253.77     251.25  269,790,200
16   Jun 1, 2025  164.17  228.22  162.60        218.63     216.46  359,459,900

In [3]:
df.shape

(17, 7)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       17 non-null     str
 1   Open       13 non-null     float64
 2   High       13 non-null     float64
 3   Low        13 non-null     float64
 4   Close      17 non-null     str
 5   Adj Close  13 non-null     float64
 6   Volume     13 non-null     str
dtypes: float64(4), str(3)
memory usage: 1.1 KB

In [5]:
df.describe()

             Open        High         Low   Adj Close
count   13.000000   13.000000   13.000000   13.000000
mean   201.226154  234.220769  181.880000  202.606923
std     43.693214   54.547488   38.029169   42.952539
min    141.620000  171.200000  134.570000  144.890000
25%    166.420000  198.000000  161.520000  163.570000
50%    197.470000  225.320000  177.070000  195.950000
75%    222.000000  260.870000  216.310000  224.360000
max    278.800000  345.720000  256.280000  279.040000

In [6]:
df.head()

          Date    Open    High     Low         Close  Adj Close       Volume
0  May 8, 2026  192.58  198.00  190.21        195.95     195.95   20,579,655
1  May 1, 2026  166.42  200.15  166.15        195.95     195.95  163,911,400
2  Apr 9, 2026     NaN     NaN     NaN  0.5 Dividend        NaN          NaN
3  Apr 1, 2026  149.09  189.18  134.57        161.39     160.83  651,513,600
4  Mar 1, 2026  141.62  171.76  136.95        147.11     146.60  621,098,900

In [7]:
df.tail()

            Date    Open    High     Low         Close  Adj Close       Volume
12   Sep 1, 2025  222.00  345.72  218.79        281.24     279.04  771,912,000
13   Aug 1, 2025  247.83  258.49  223.11        226.13     224.36  218,404,000
14  Jul 10, 2025     NaN     NaN     NaN  0.5 Dividend        NaN          NaN
15   Jul 1, 2025  219.30  260.87  216.31        253.77     251.25  269,790,200
16   Jun 1, 2025  164.17  228.22  162.60        218.63     216.46  359,459,900

In [8]:
df.columns

Index(['Date', 'Open', 'High', 'Low', 'Close', 'Adj Close', 'Volume'], dtype='str')

In [9]:
df[df['High']==df['High'].max()]["Date"]

12    Sep 1, 2025
Name: Date, dtype: str

In [10]:
df['High'].max()

np.float64(345.72)

In [11]:
df["High"].min()

np.float64(171.2)

In [12]:
df.isnull()

     Date   Open   High    Low  Close  Adj Close  Volume
0   False  False  False  False  False      False   False
1   False  False  False  False  False      False   False
2   False   True   True   True  False       True    True
3   False  False  False  False  False      False   False
4   False  False  False  False  False      False   False
5   False  False  False  False  False      False   False
6   False   True   True   True  False       True    True
7   False  False  False  False  False      False   False
8   False  False  False  False  False      False   False
9   False  False  False  False  False      False   False
10  False   True   True   True  False       True    True
11  False  False  False  False  False      False   False
12  False  False  False  False  False      False   False
13  False  False  False  False  False      False   False
14  False   True   True   True  False       True    True
15  False  False  False  False  False      False   False
16  False  False  False  False  False      False   False

In [22]:
dividend_rows=df[df["Close"].astype(str).str.contains("Dividend",na=False)]
dividend_rows

            Date  Open  High  Low         Close  Adj Close Volume
2    Apr 9, 2026   NaN   NaN  NaN  0.5 Dividend        NaN    NaN
6    Jan 9, 2026   NaN   NaN  NaN  0.5 Dividend        NaN    NaN
10   Oct 9, 2025   NaN   NaN  NaN  0.5 Dividend        NaN    NaN
14  Jul 10, 2025   NaN   NaN  NaN  0.5 Dividend        NaN    NaN

In [25]:
total_dividends = dividend_rows.shape[0]
total_dividends

4

In [ ]:
df[df["Close"].astype(str).str.contains("Dividend")].count()

In [ ]:
dividend_rows["Dividend Amount"] = (#creating new column dividend amount
    dividend_rows["Close"]#selecting column close in dividend rows
    .str.extract(r'(\d+\.?\d*)')#extracting the number from the text
    .astype(float)#convert text into float
)

In [30]:
average_dividend = dividend_rows["Dividend Amount"].mean()
average_dividend

np.float64(0.5)