In [1]:
import numpy as np 
import pandas as pd

In [43]:
df=pd.read_csv('student-mat.csv')
df

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,NaN,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...
995,NaN,Kenneth Murray,Male,85.0,20.0,NaN,1.0,High,72.0,0.8,80.0,True
996,4497.0,Amy Stout,Female,91.0,NaN,86.0,0.0,High,90.0,3.9,80.0,True
997,1886.0,NaN,Male,85.0,8.0,82.0,2.0,Low,68.0,0.4,54.0,False
998,7636.0,Joseph Sherman,Male,88.0,17.0,60.0,2.0,High,85.0,0.9,53.0,True
999,8021.0,Maria Walls,Female,88.0,10.0,90.0,1.0,Medium,NaN,2.4,94.0,True

In [3]:
df.shape

(1000, 12)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    str
 2   Gender                     952 non-null    str
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          949 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  956 non-null    float64
 7   ParentalSupport            978 non-null    str
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                975 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(1), str(3)
memory usage: 93.9+ KB

In [5]:
df.head(10)

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,NaN,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True
5,6.0,Olivia,Female,95.0,30.0,88.0,1.0,High,NaN,2.8,97.0,False
6,7.0,Daniel,Male,70.0,8.0,60.0,0.0,Low,62.0,4.5,96.0,False
7,8.0,Sophia,Female,NaN,17.0,77.0,1.0,Medium,78.0,1.0,70.0,True
8,9.0,James,Male,82.0,NaN,70.0,2.0,Low,72.0,3.6,50.0,False
9,10.0,Isabella,Female,91.0,22.0,86.0,3.0,High,88.0,2.9,59.0,True

In [6]:
df.isna().sum()

StudentID                    40
Name                         34
Gender                       48
AttendanceRate               40
StudyHoursPerWeek            51
PreviousGrade                33
ExtracurricularActivities    44
ParentalSupport              22
FinalGrade                   40
Study Hours                  25
Attendance (%)               41
Online Classes Taken         25
dtype: int64

In [7]:
df.columns

Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study Hours', 'Attendance (%)', 'Online Classes Taken'],
      dtype='str')

In [46]:
df.sample(4)

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
530,4016.0,Julia Brooks,Female,78.0,15.0,88.0,0.0,Medium,NaN,2.2,90.0,False
692,2552.0,Alison Williams,Female,88.0,20.0,86.0,2.0,Medium,62.0,1.0,100.0,True
388,6664.0,Robin Spears,Female,78.0,12.0,86.0,1.0,High,68.0,2.5,80.0,False
863,4153.0,Charles Vincent,Male,78.0,NaN,65.0,2.0,High,88.0,2.7,100.0,True

In [8]:
df.tail(5)

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
995,NaN,Kenneth Murray,Male,85.0,20.0,NaN,1.0,High,72.0,0.8,80.0,True
996,4497.0,Amy Stout,Female,91.0,NaN,86.0,0.0,High,90.0,3.9,80.0,True
997,1886.0,NaN,Male,85.0,8.0,82.0,2.0,Low,68.0,0.4,54.0,False
998,7636.0,Joseph Sherman,Male,88.0,17.0,60.0,2.0,High,85.0,0.9,53.0,True
999,8021.0,Maria Walls,Female,88.0,10.0,90.0,1.0,Medium,NaN,2.4,94.0,True

In [9]:
df.dtypes

StudentID                    float64
Name                             str
Gender                           str
AttendanceRate               float64
StudyHoursPerWeek            float64
PreviousGrade                float64
ExtracurricularActivities    float64
ParentalSupport                  str
FinalGrade                   float64
Study Hours                  float64
Attendance (%)               float64
Online Classes Taken          object
dtype: object

In [10]:
df.describe()

,StudentID,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,FinalGrade,Study Hours,Attendance (%)
count,960.000000,960.000000,949.000000,967.000000,956.000000,960.000000,975.000000,959.000000
mean,5416.019792,85.510417,17.636459,77.598759,1.521967,80.030208,2.404718,77.248175
std,2653.748319,7.332125,6.272771,10.006640,1.045829,9.493652,1.619573,19.298148
min,1.000000,70.000000,8.000000,60.000000,0.000000,62.000000,-5.000000,50.000000
25%,3113.500000,82.000000,12.000000,70.000000,1.000000,72.000000,1.200000,63.000000
50%,5396.500000,88.000000,18.000000,78.000000,1.500000,80.000000,2.500000,76.000000
75%,7754.750000,91.000000,22.000000,86.000000,2.000000,88.000000,3.700000,89.000000
max,9998.000000,95.000000,30.000000,90.000000,3.000000,92.000000,5.000000,200.000000

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df["Gender"].unique()

<StringArray>
['Male', 'Female', nan]
Length: 3, dtype: str

In [13]:
df.select_dtypes(include=np.number)

,StudentID,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,FinalGrade,Study Hours,Attendance (%)
0,1.0,85.0,15.0,78.0,1.0,80.0,4.8,59.0
1,2.0,90.0,20.0,85.0,2.0,87.0,2.2,70.0
2,3.0,78.0,10.0,65.0,0.0,68.0,NaN,92.0
3,4.0,92.0,25.0,90.0,3.0,92.0,2.9,96.0
4,5.0,NaN,18.0,82.0,2.0,85.0,4.1,97.0
...,...,...,...,...,...,...,...,...
995,NaN,85.0,20.0,NaN,1.0,72.0,0.8,80.0
996,4497.0,91.0,NaN,86.0,0.0,90.0,3.9,80.0
997,1886.0,85.0,8.0,82.0,2.0,68.0,0.4,54.0
998,7636.0,88.0,17.0,60.0,2.0,85.0,0.9,53.0
999,8021.0,88.0,10.0,90.0,1.0,NaN,2.4,94.0

In [14]:
df.select_dtypes(include=object)

C:\Users\Safeer Khan\AppData\Local\Temp\ipykernel_2964\4102662033.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include=object)

               Name  Gender ParentalSupport Online Classes Taken
0              John    Male            High                False
1             Sarah  Female          Medium                 True
2              Alex    Male             Low                False
3           Michael    Male            High                False
4              Emma  Female          Medium                 True
..              ...     ...             ...                  ...
995  Kenneth Murray    Male            High                 True
996       Amy Stout  Female            High                 True
997             NaN    Male             Low                False
998  Joseph Sherman    Male            High                 True
999     Maria Walls  Female          Medium                 True

[1000 rows x 4 columns]

In [16]:
#how many student are in the dataset?
df.shape[0]

1000

In [20]:
#which column has highest average value?
df.mean(numeric_only=True).idxmax()

'StudentID'

In [ ]:
#Are there any missing values
df.isna().any()

StudentID                    True
Name                         True
Gender                       True
AttendanceRate               True
StudyHoursPerWeek            True
PreviousGrade                True
ExtracurricularActivities    True
ParentalSupport              True
FinalGrade                   True
Study Hours                  True
Attendance (%)               True
Online Classes Taken         True
dtype: bool

In [22]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [24]:
df.dtypes[df.dtypes=='object']

Online Classes Taken    object
dtype: object

In [27]:
df.select_dtypes(include='object').columns

C:\Users\Safeer Khan\AppData\Local\Temp\ipykernel_2964\3732952691.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include='object').columns

Index(['Name', 'Gender', 'ParentalSupport', 'Online Classes Taken'], dtype='str')

In [29]:
df.select_dtypes(include=np.number).columns

Index(['StudentID', 'AttendanceRate', 'StudyHoursPerWeek', 'PreviousGrade',
       'ExtracurricularActivities', 'FinalGrade', 'Study Hours',
       'Attendance (%)'],
      dtype='str')

In [44]:
num_df=df.select_dtypes(include=np.number)
colerration=num_df.corr()
colerration["FinalGrade"].sort_values(ascending=False)

FinalGrade                   1.000000
StudentID                    0.078321
Attendance (%)               0.040807
StudyHoursPerWeek            0.035586
Study Hours                  0.032912
PreviousGrade                0.003982
AttendanceRate              -0.014768
ExtracurricularActivities   -0.024171
Name: FinalGrade, dtype: float64